# Make sure to replace placeholder paths to config files and model directories

version: "3.7"

services:

  # The speech API service.
  api:
    image: quay.io/deepgram/onprem-api:release-240104

    # Added 29 Jan 2024 for GCP logging.
    logging:
      driver: gcplogs

    # Here we expose the API port to the host machine. The container port
    # (right-hand side) must match the port that the API service is listening
    # on (from its configuration file).
    ports:
      - "8080:8080"

    # Make sure you `export` your on-prem API key secret in your local environment
    environment:  
      DEEPGRAM_API_KEY: "f4fada601452ad0159e320b1dc78e5fcdd72800d"

    # The path on the left of the colon ':' should point to files/directories on the host machine.
    # The path on the right of the colon ':' is an in-container path. It must match the path
    #     specified in the `command` header below.
    volumes:
    - "/home/deepgram/config/api.toml:/api.toml:ro,Z"

    # Invoke the API server
    command: -v serve /api.toml 
  
  # The speech engine service.
  engine:
    image: quay.io/deepgram/onprem-engine:release-240104

    # Added 29 Jan 2024 for GCP logging.
    logging:
      driver: gcplogs

    # Change the default runtime.
    runtime: nvidia

    ports:
      - "9991:9991"

    # Make sure you `export` your on-prem API key secret in your local environment
    environment:
      DEEPGRAM_API_KEY: "f4fada601452ad0159e320b1dc78e5fcdd72800d"

    # The path on the left of the colon ':' should point to files/directories on the host machine.
    # The path on the right of the colon ':' is an in-container path.
    volumes:
    # In-container models path below must match the one specified in the Engine configuration file. The default location is "/models"
      - "/home/deepgram/models:/models:ro,Z"
    # In-container config path below must match the path specified in the `command` header below.
      - "/home/deepgram/config/engine.toml:/engine.toml:ro,Z"

    # Invoke the Engine service
    command: -v serve /engine.toml 